import 'package:flutter/material.dart';
import 'app_colors.dart';

class LiveRouteScreen extends StatelessWidget{ const LiveRouteScreen({super.key});
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Padding(padding: const EdgeInsets.all(16), child:Container(decoration:cardDecoration(radius:24), child:Column(children:[
    Padding(padding: const EdgeInsets.all(14), child:Row(children:[const CircleAvatar(child:Icon(Icons.person)), const SizedBox(width:10), const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[Text('Ahmed is on the way', style: TextStyle(fontWeight:FontWeight.bold)), Text('12 min away', style: TextStyle(color:AppColors.muted,fontSize:12))])), IconButton(onPressed:(){}, icon: const Icon(Icons.phone,color:AppColors.primary))])),
    Expanded(child:CustomPaint(painter:_MapPainter(), child:Container(alignment:Alignment.center, child: const Icon(Icons.directions_car,color:Colors.black,size:34)))),
    Padding(padding: const EdgeInsets.all(18), child:Column(children:[const Row(mainAxisAlignment:MainAxisAlignment.spaceAround, children:[_Metric('ETA','12 min'), _Metric('Distance','8.6 km'), _Metric('Traffic','Medium')]), const SizedBox(height:16), const Align(alignment:Alignment.centerLeft, child:Text('New faster route found!', style: TextStyle(fontWeight:FontWeight.bold))), const Align(alignment:Alignment.centerLeft, child:Text('Save 5 min', style: TextStyle(color:AppColors.muted))), const SizedBox(height:14), SizedBox(width:double.infinity,height:52, child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:AppColors.primary,foregroundColor:Colors.white), onPressed:(){}, child: const Text('Accept New Route')))]))
  ])))));
}
class _Metric extends StatelessWidget{final String a,b; const _Metric(this.a,this.b); @override Widget build(BuildContext c)=>Column(children:[Text(a,style: const TextStyle(color:AppColors.muted,fontSize:12)), Text(b,style: const TextStyle(fontWeight:FontWeight.bold))]);}
class _MapPainter extends CustomPainter{ @override void paint(Canvas c,Size s){final p=Paint()..color=Colors.grey.shade200; c.drawRect(Offset.zero&s,p); final line=Paint()..color=AppColors.primary..strokeWidth=5..style=PaintingStyle.stroke; final path=Path()..moveTo(s.width*.25,s.height*.15)..lineTo(s.width*.65,s.height*.22)..lineTo(s.width*.58,s.height*.55)..lineTo(s.width*.78,s.height*.75); c.drawPath(path,line); c.drawCircle(Offset(s.width*.78,s.height*.75),10,Paint()..color=Colors.pink);} @override bool shouldRepaint(covariant CustomPainter oldDelegate)=>false;}