import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../data/mock_data.dart';
import '../models/route.dart' as app_route;
import '../providers/app_provider.dart';
import 'app_colors.dart';

class PublishTripScreen extends StatefulWidget{ const PublishTripScreen({super.key}); @override State<PublishTripScreen> createState()=>_PublishTripScreenState();}
class _PublishTripScreenState extends State<PublishTripScreen>{String start='6 October',end='Maadi'; int seats=3; double cost=40; bool female=false; final time=TextEditingController(text:'5:00 PM');
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title: const Text('Create New Ride')), body:ListView(padding: const EdgeInsets.all(18), children:[_drop('From',start,(v)=>setState(()=>start=v!)), const SizedBox(height:12), _drop('To',end,(v)=>setState(()=>end=v!)), const SizedBox(height:12), _field('Departure Time',time,Icons.access_time), const SizedBox(height:12), _step('Available Seats',seats,(v)=>setState(()=>seats=v)), const SizedBox(height:12), Text('Price per Seat: ${cost.round()} EGP'), Slider(value:cost,min:20,max:100,onChanged:(v)=>setState(()=>cost=v)), SwitchListTile(value:female,onChanged:(v)=>setState(()=>female=v), title: const Text('Female Only'), secondary: const Icon(Icons.female,color:Colors.pink)), const SizedBox(height:16), SizedBox(height:54, child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:AppColors.primary,foregroundColor:Colors.white), onPressed:(){context.read<AppProvider>().publishRoute(app_route.Route(id:DateTime.now().millisecondsSinceEpoch.toString(), start:start,end:end,time:time.text,cost:cost,transfers:0,driver_name:context.read<AppProvider>().currentUser?.name??'Driver',driver_rating:4.8,car_model:'Hyundai Elantra',available_seats:seats,total_seats:seats,female_only:female)); Navigator.pop(context);}, child: const Text('Publish Ride')))]));
  Widget _drop(String label,String val,ValueChanged<String?> on)=>Container(padding: const EdgeInsets.symmetric(horizontal:12), decoration:cardDecoration(radius:12), child:DropdownButtonFormField(value:val, decoration:InputDecoration(labelText:label,border:InputBorder.none,prefixIcon: const Icon(Icons.location_on_outlined,color:AppColors.primary)), items:MockData.areas.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(), onChanged:on));
  Widget _field(String l,TextEditingController c,IconData i)=>TextField(controller:c, decoration:InputDecoration(labelText:l,prefixIcon:Icon(i,color:AppColors.primary),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:BorderSide.none)));
  Widget _step(String label,int v,ValueChanged<int> on)=>Container(padding: const EdgeInsets.all(14), decoration:cardDecoration(radius:12), child:Row(children:[Text(label), const Spacer(), IconButton(onPressed:()=>on(v>1?v-1:v), icon: const Icon(Icons.remove)), Text('$v'), IconButton(onPressed:()=>on(v+1), icon: const Icon(Icons.add))]));
}